"""
Shared data loading, analysis, and UI helpers for the Fantasy Football
Analytics Dashboard multipage app. Imported by streamlit_app_pick.py
(the st.navigation() router) and every page in app_pages/.

This module must not call any Streamlit rendering commands at import
time - st.set_page_config() has to be the first Streamlit call in the
app, so all UI here lives inside functions the router/pages call
explicitly.
"""

import streamlit as st
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
import numpy as np
import html
import re
from pathlib import Path


# Fixed position -> color mapping, shared by every chart/table that
# breaks data out by position, so a position keeps the same color
# everywhere regardless of which positions happen to be selected in
# the sidebar filter (Plotly's default coloring reassigns colors when
# the set of categories present in the data changes).
POSITION_COLORS = {
    'QB': '#636EFA',
    'RB': '#EF553B',
    'WR': '#00CC96',
    'TE': '#AB63FA',
    'DEF': '#FFA15A',
    'K': '#19D3F3',
    'Unknown': '#7F7F7F',
}


def configure_page(page_title, page_icon="🏈"):
    """Call once, first thing, in the entry-point router script only -
    st.set_page_config() errors if called more than once per app run."""
    st.set_page_config(
        page_title=page_title,
        page_icon=page_icon,
        layout="wide",
        initial_sidebar_state="expanded"
    )


def inject_custom_css():
    st.markdown("""
    <style>
        .main-header {
            font-size: 3rem;
            color: #1f77b4;
            text-align: center;
            margin-bottom: 2rem;
        }
        .metric-container {
            background-color: #f0f2f6;
            padding: 1rem;
            border-radius: 0.5rem;
            margin: 0.5rem 0;
        }
    </style>
    """, unsafe_allow_html=True)


def add_trendline_if_available(fig, df, x_col, y_col):
    """Add trend line if statsmodels is available, otherwise skip"""
    try:
        import statsmodels.api as sm

        x = df[x_col].values
        y = df[y_col].values

        mask = ~(np.isnan(x) | np.isnan(y))
        x_clean = x[mask]
        y_clean = y[mask]

        if len(x_clean) > 1:
            X = sm.add_constant(x_clean)
            model = sm.OLS(y_clean, X).fit()

            x_trend = np.linspace(x_clean.min(), x_clean.max(), 100)
            y_trend = model.params[0] + model.params[1] * x_trend

            fig.add_scatter(
                x=x_trend,
                y=y_trend,
                mode='lines',
                name='Trend',
                line=dict(color='red', dash='dash'),
                showlegend=False
            )
    except ImportError:
        pass
    except Exception:
        pass

    return fig


@st.cache_data
def load_all_data():
    """Load all CSV files from data folder"""
    data_dir = Path("ff-dash/data")
    file_path = "ff-dash/data/2021-2024_stats.csv"
    master_df = pd.read_csv(file_path)

    if not master_df.empty and 'position' in master_df.columns:
        master_df = fix_free_agent_positions(master_df)

    adp_files = ["ADP_2022.csv", "ADP_2023.csv", "ADP_2024.csv", "ADP_2025.csv"]
    adp_data = []
    for filename in adp_files:
        file_path = data_dir / filename
        if file_path.exists():
            df = pd.read_csv(file_path)
            adp_data.append(df)

    adp_df = pd.concat(adp_data, ignore_index=True) if adp_data else pd.DataFrame()

    return master_df, adp_df


@st.cache_data
def load_draft_data():
    """
    Load draft data from CSV (generated by Yahoo API function)
    Expected columns: year, round, pick, team_name, player_name, position, season_points
    """
    draft_data_path = Path("ff-dash/data/2021-2025_draft_results.csv")

    if draft_data_path.exists():
        draft_df = pd.read_csv(draft_data_path)
        return draft_df
    else:
        return pd.DataFrame(columns=[
            'year', 'round', 'pick', 'team_name',
            'player_name', 'position', 'season_points'
        ])


def fix_free_agent_positions(df):
    """
    Fix missing position data for Free Agent players by forward-filling
    their position from when they were rostered
    """
    df = df.copy()
    df = df.sort_values(['player_name_full', 'year', 'week'])

    df['position'] = df.groupby(['player_name_full', 'year'])['position'].ffill()
    df['position'] = df.groupby('player_name_full')['position'].ffill()
    df['position'] = df.groupby('player_name_full')['position'].bfill()

    df = guess_missing_positions(df)

    return df


def guess_missing_positions(df):
    """
    Make educated guesses for any remaining missing positions based on stats
    """
    missing_pos = df['position'].isna()

    if missing_pos.sum() > 0:
        is_qb = (df['Pass Yds'].notna() & (df['Pass Yds'] > 0)) | (df['Pass TD'].notna() & (df['Pass TD'] > 0))
        df.loc[missing_pos & is_qb, 'position'] = 'QB'

        is_kicker = ((df['FG 0-19'].notna() & (df['FG 0-19'] > 0)) |
                    (df['FG 20-29'].notna() & (df['FG 20-29'] > 0)) |
                    (df['FG 30-39'].notna() & (df['FG 30-39'] > 0)) |
                    (df['FG 40-49'].notna() & (df['FG 40-49'] > 0)) |
                    (df['FG 50+'].notna() & (df['FG 50+'] > 0)) |
                    (df['PAT Made'].notna() & (df['PAT Made'] > 0)))
        df.loc[missing_pos & is_kicker, 'position'] = 'K'

        is_def = ((df['Sack'].notna() & (df['Sack'] > 0)) |
                 (df['Fum Rec'].notna() & (df['Fum Rec'] > 0)) |
                 (df['Safe'].notna() & (df['Safe'] > 0)) |
                 (df['Pts Allow 0'].notna()))
        df.loc[missing_pos & is_def, 'position'] = 'DEF'

        is_wr = ((df['Rec'].notna() & (df['Rec'] > 0)) |
                (df['Rec Yds'].notna() & (df['Rec Yds'] > 0)) |
                (df['Rec TD'].notna() & (df['Rec TD'] > 0))) & ~is_qb
        df.loc[missing_pos & is_wr, 'position'] = 'WR'

        is_rb = ((df['Rush Yds'].notna() & (df['Rush Yds'] > 0)) |
                (df['Rush TD'].notna() & (df['Rush TD'] > 0))) & ~is_qb & ~is_wr
        df.loc[missing_pos & is_rb, 'position'] = 'RB'

        df['position'] = df['position'].fillna('UNKNOWN')

    return df


def render_sidebar_filters(master_df):
    """
    Renders the year/position sidebar controls and persists the selection
    in st.session_state so it survives navigation between pages.

    Streamlit's classic pages/-directory multipage apps reset a widget's
    state when a *different* page creates a widget with the same key
    (each page has its own widget registry), so a plain `key=` alone does
    not survive navigation. The standard workaround - and what's used
    here - is a separate "persist" key that isn't owned by any widget,
    combined with `value=` + `on_change` to keep it in sync with the
    widget on every rerun.

    The year list is master_df's years unioned with load_draft_data()'s
    years, not just master_df's - draft data can be ahead of the weekly
    stats file (a season's draft happens before any weekly stats exist
    for it), and this way every page offers the same year list
    automatically instead of each page having to opt in separately.
    """
    st.sidebar.header("🎛️ Controls")

    st.sidebar.subheader("📅 Select Years")
    draft_df_years = load_draft_data()
    extra_years_set = set(draft_df_years['year'].unique()) if not draft_df_years.empty else set()
    years = sorted(set(master_df['year'].unique()) | extra_years_set)

    cols = st.sidebar.columns(len(years))
    selected_years = []
    for i, year in enumerate(years):
        persist_key = f"year_{year}_persist"
        widget_key = f"year_{year}_widget"
        if persist_key not in st.session_state:
            st.session_state[persist_key] = True

        def _sync_year(persist_key=persist_key, widget_key=widget_key):
            st.session_state[persist_key] = st.session_state[widget_key]

        with cols[i]:
            checked = st.checkbox(
                str(year),
                value=st.session_state[persist_key],
                key=widget_key,
                on_change=_sync_year,
            )
        if checked:
            selected_years.append(year)

    positions = master_df['position'].dropna().astype(str).unique()
    positions = sorted([pos for pos in positions if pos != 'nan'])
    if "selected_positions_persist" not in st.session_state:
        st.session_state["selected_positions_persist"] = positions

    def _sync_positions():
        st.session_state["selected_positions_persist"] = st.session_state["selected_positions_widget"]

    selected_positions = st.sidebar.multiselect(
        "🏃‍♂️ Select Positions",
        positions,
        default=st.session_state["selected_positions_persist"],
        key="selected_positions_widget",
        on_change=_sync_positions,
    )

    return selected_years, selected_positions


def apply_filters(master_df, selected_years, selected_positions):
    return master_df[
        (master_df['year'].isin(selected_years)) &
        (master_df['position'].isin(selected_positions))
    ]


def render_data_summary(filtered_df):
    st.sidebar.markdown("---")
    st.sidebar.metric("📊 Total Records", len(filtered_df))
    st.sidebar.metric("👤 Unique Players", filtered_df['player_name_full'].nunique())
    st.sidebar.metric("🏆 Teams", filtered_df['team_name'].nunique())


# ANALYSIS FUNCTIONS

def calculate_avg_points_per_player(df):
    """Analysis 1: Average points per player"""
    avg_points_per_player = df.groupby(['player_name_full', 'position']).agg({
        'player_fantasy_pts': ['mean', 'count', 'std'],
        'year': 'first'
    }).round(2)

    avg_points_per_player.columns = ['avg_points_per_week', 'games_played', 'std_dev', 'year']
    avg_points_per_player = avg_points_per_player.reset_index()
    avg_points_per_player = avg_points_per_player[avg_points_per_player['games_played'] >= 4]

    return avg_points_per_player.sort_values('avg_points_per_week', ascending=False)


def calculate_avg_points_per_position(df):
    """Analysis 3: Average points per position"""
    avg_points_by_position = df.groupby(['position', 'year']).agg({
        'player_fantasy_pts': ['mean', 'median', 'count'],
        'player_name_full': 'nunique'
    }).round(2)

    avg_points_by_position.columns = ['mean_points', 'median_points', 'total_games', 'unique_players']
    return avg_points_by_position.reset_index()


def calculate_position_volatility(df):
    """Analysis 4: Position volatility"""
    position_volatility = df.groupby(['position', 'year']).agg({
        'player_fantasy_pts': ['std', 'mean', 'min', 'max']
    }).round(2)

    position_volatility.columns = ['std_dev_points', 'mean_points', 'min_points', 'max_points']
    position_volatility = position_volatility.reset_index()
    position_volatility['coeff_of_variation'] = position_volatility['std_dev_points'] / position_volatility['mean_points']

    return position_volatility


def create_player_tiers_by_position(df, method='natural_breaks'):
    """
    Analysis 6: Player tiers using natural breakpoints instead of quartiles
    Tier 1 = Best players, Tier 4 = Worst players
    """
    player_season_avg = df.groupby(['player_name_full', 'position', 'year']).agg({
        'player_fantasy_pts': 'mean',
        'week': 'count'
    }).reset_index()

    player_season_avg = player_season_avg[player_season_avg['week'] >= 8]

    def assign_natural_tiers(group):
        if len(group) < 8:  # Need minimum players for meaningful tiers
            return group

        group = group.sort_values('player_fantasy_pts', ascending=False)
        group['rank'] = range(1, len(group) + 1)

        pos = group['position'].iloc[0]

        if pos in ['QB', 'TE']:  # Shallow positions
            tier_breaks = [0.15, 0.40, 0.75, 1.0]
        elif pos in ['K', 'DEF']:  # Very shallow
            tier_breaks = [0.20, 0.50, 0.80, 1.0]
        else:  # RB, WR - deeper positions
            tier_breaks = [0.10, 0.30, 0.65, 1.0]

        n_players = len(group)
        tier_cutoffs = [int(n_players * pct) for pct in tier_breaks]

        conditions = [
            group['rank'] <= tier_cutoffs[0],
            group['rank'] <= tier_cutoffs[1],
            group['rank'] <= tier_cutoffs[2],
            group['rank'] <= tier_cutoffs[3]
        ]

        choices = ['Tier 1', 'Tier 2', 'Tier 3', 'Tier 4']
        group['tier'] = np.select(conditions, choices, default='Tier 4')

        return group

    tiered_groups = [assign_natural_tiers(group) for _, group in player_season_avg.groupby(['position', 'year'])]
    player_tiers = pd.concat(tiered_groups, ignore_index=True) if tiered_groups else player_season_avg
    return player_tiers


def get_season_point_totals(master_df, draft_df, selected_years, selected_positions):
    """
    Season point total per player/position/year, sourced from weekly
    stats (master_df) where available and supplemented by
    draft_results.csv's season_points for any selected year master_df
    doesn't cover yet - e.g. a season's draft happens before any weekly
    stats exist for it, so a new year shows up in draft_results.csv
    first.

    Weekly-stats years require >=4 games played to qualify (filters out
    tiny/inactive-week noise); draft-sourced years have no games count
    to filter on, so every drafted player at that position/year is
    included as-is. Note draft-sourced years only cover the ~160
    players actually drafted that year, not the full rostered/
    free-agent pool weekly-stats years have (~469 players total) - so
    a draft-sourced year's numbers aren't directly apples-to-apples
    with a weekly-stats year's.

    Returns columns: player_name_full, position, year, season_points,
    games (NaN for draft-sourced rows).
    """
    master_years = set(master_df['year'].unique())

    weekly_totals = master_df[
        master_df['year'].isin(selected_years) & master_df['position'].isin(selected_positions)
    ].groupby(['player_name_full', 'position', 'year']).agg(
        season_points=('player_fantasy_pts', 'sum'),
        games=('week', 'count'),
    ).reset_index()
    weekly_totals = weekly_totals[weekly_totals['games'] >= 4]

    draft_only_years = [y for y in selected_years if y not in master_years]

    if draft_only_years and draft_df is not None and not draft_df.empty:
        draft_totals = draft_df[
            draft_df['year'].isin(draft_only_years) & draft_df['position'].isin(selected_positions)
        ][['player_name', 'position', 'year', 'season_points']].rename(
            columns={'player_name': 'player_name_full'}
        )
        draft_totals['games'] = np.nan
        combined = pd.concat([weekly_totals, draft_totals], ignore_index=True)
    else:
        combined = weekly_totals

    return combined


def create_player_rank_analysis(season_totals):
    """
    Rank players within each year by season point total.

    Takes the output of get_season_point_totals() - one row per
    player/position/year with a season_points total - rather than raw
    weekly rows, so it works for both weekly-stats years and
    draft-results-only years alike.
    """
    ranked_players = season_totals.copy()

    ranked_players['overall_rank'] = (
        ranked_players.groupby('year')['season_points']
        .rank(method='first', ascending=False)
        .astype(int)
    )

    ranked_players = ranked_players.sort_values(['year', 'overall_rank']).reset_index(drop=True)

    return ranked_players


PERCENTILE_BAND_LABELS = ['Top 10% (90%+)', '75-89%', '50-74%', '25-49%', 'Bottom 25% (<25%)']


def calculate_position_percentile_bands(season_totals):
    """
    For each (position, year), rank players by their season point total
    and bucket them into fixed percentile bands - unlike
    create_player_tiers_by_position, these band cutoffs (90th, 75th,
    50th, 25th percentile) are the same for every position, so bands
    are directly comparable across positions rather than tuned per
    position's shape.

    Takes the output of get_season_point_totals() rather than raw
    weekly rows, so it works for both weekly-stats years and
    draft-results-only years alike.

    Returns one row per (position, year, band) with that band's average
    season point total and how many players fall in it.
    """
    season_totals = season_totals.copy()

    season_totals['percentile'] = (
        season_totals.groupby(['position', 'year'])['season_points']
        .rank(pct=True, ascending=True)
    )

    bins = [-0.01, 0.25, 0.50, 0.75, 0.90, 1.01]
    season_totals['band'] = pd.cut(
        season_totals['percentile'], bins=bins, labels=list(reversed(PERCENTILE_BAND_LABELS))
    )

    band_stats = season_totals.groupby(['position', 'year', 'band'], observed=True).agg(
        avg_points=('season_points', 'mean'),
        player_count=('season_points', 'count'),
    ).reset_index()

    return band_stats


def format_percentile_band_table(band_stats):
    """
    Pivot calculate_position_percentile_bands()'s long output into a
    display-ready table: one row per (position, year), one column per
    band, each cell showing that band's average season points and
    player count as a single readable string.
    """
    if band_stats.empty:
        return pd.DataFrame(columns=['Position', 'Year'] + PERCENTILE_BAND_LABELS)

    band_stats = band_stats.copy()
    band_stats['cell'] = band_stats.apply(
        lambda r: f"{r['avg_points']:.1f} pts (n={r['player_count']})", axis=1
    )

    pivoted = band_stats.pivot_table(
        index=['position', 'year'], columns='band', values='cell', aggfunc='first', observed=True
    )
    pivoted = pivoted.reindex(columns=PERCENTILE_BAND_LABELS)
    pivoted = pivoted.fillna('–')
    pivoted = pivoted.reset_index().rename(columns={'position': 'Position', 'year': 'Year'})
    pivoted = pivoted.sort_values(['Position', 'Year']).reset_index(drop=True)

    return pivoted


def create_team_analysis(df):
    """Analysis 7: Team analysis"""
    team_performance = df.groupby(['team_name', 'year']).agg({
        'player_fantasy_pts': 'sum',
        'week': 'nunique'
    }).reset_index()

    team_performance['avg_points_per_week'] = team_performance['player_fantasy_pts'] / team_performance['week']
    return team_performance


def analyze_positional_scarcity(df):
    """
    Analyze which positions have the biggest drop-off from elite to average players
    This helps determine draft strategy: where is elite talent most scarce?
    """
    player_season_avg = df.groupby(['player_name_full', 'position', 'year']).agg({
        'player_fantasy_pts': 'mean',
        'week': 'count'
    }).reset_index()

    player_season_avg = player_season_avg[player_season_avg['week'] >= 8]

    scarcity_analysis = []

    for position in player_season_avg['position'].unique():
        pos_data = player_season_avg[player_season_avg['position'] == position]

        if len(pos_data) < 10:  # Need sufficient sample
            continue

        pos_data = pos_data.sort_values('player_fantasy_pts', ascending=False)

        total_players = len(pos_data)

        elite_cutoff = max(1, int(total_players * 0.05))
        elite_avg = pos_data.head(elite_cutoff)['player_fantasy_pts'].mean()

        top10_cutoff = max(1, int(total_players * 0.10))
        top10_avg = pos_data.head(top10_cutoff)['player_fantasy_pts'].mean()

        starter_cutoff = max(1, int(total_players * 0.25))
        starter_avg = pos_data.head(starter_cutoff)['player_fantasy_pts'].mean()

        mid_start = starter_cutoff
        mid_end = max(1, int(total_players * 0.50))
        mid_avg = pos_data.iloc[mid_start:mid_end]['player_fantasy_pts'].mean()

        replacement_start = mid_end
        replacement_end = max(1, int(total_players * 0.75))
        replacement_avg = pos_data.iloc[replacement_start:replacement_end]['player_fantasy_pts'].mean()

        elite_to_starter_drop = elite_avg - starter_avg
        elite_to_mid_drop = elite_avg - mid_avg
        top10_to_starter_drop = top10_avg - starter_avg
        starter_to_replacement_drop = starter_avg - replacement_avg

        scarcity_analysis.append({
            'position': position,
            'total_players': total_players,
            'elite_avg': round(elite_avg, 1),
            'top10_avg': round(top10_avg, 1),
            'starter_avg': round(starter_avg, 1),
            'mid_avg': round(mid_avg, 1),
            'replacement_avg': round(replacement_avg, 1),
            'elite_to_starter_drop': round(elite_to_starter_drop, 1),
            'elite_to_mid_drop': round(elite_to_mid_drop, 1),
            'top10_to_starter_drop': round(top10_to_starter_drop, 1),
            'starter_to_replacement_drop': round(starter_to_replacement_drop, 1),
            'elite_count': elite_cutoff,
            'top10_count': top10_cutoff,
            'starter_count': starter_cutoff
        })

    return pd.DataFrame(scarcity_analysis)


def analyze_elite_vs_depth_strategy(df):
    """
    Compare teams that drafted elite QBs vs teams that went RB/WR heavy early
    """
    player_season_avg = df.groupby(['player_name_full', 'position', 'year']).agg({
        'player_fantasy_pts': 'mean',
        'week': 'count'
    }).reset_index()

    player_season_avg = player_season_avg[player_season_avg['week'] >= 8]

    var_analysis = []

    for position in player_season_avg['position'].unique():
        pos_data = player_season_avg[player_season_avg['position'] == position]

        if len(pos_data) < 10:
            continue

        pos_data = pos_data.sort_values('player_fantasy_pts', ascending=False)

        replacement_cutoff = int(len(pos_data) * 0.75)
        replacement_level = pos_data.iloc[replacement_cutoff]['player_fantasy_pts']

        pos_data['value_above_replacement'] = pos_data['player_fantasy_pts'] - replacement_level

        elite_count = max(1, int(len(pos_data) * 0.05))
        elite_var = pos_data.head(elite_count)['value_above_replacement'].mean()

        var_analysis.append({
            'position': position,
            'replacement_level': round(replacement_level, 1),
            'elite_var': round(elite_var, 1),
            'elite_count': elite_count
        })

    return pd.DataFrame(var_analysis)


# DRAFT ANALYSIS FUNCTIONS

def analyze_draft_strategy_effectiveness(draft_df):
    """
    Analyze which draft strategies led to better team performance
    """
    if draft_df.empty:
        return pd.DataFrame()

    team_season_totals = draft_df.groupby(['team_name', 'year']).agg({
        'season_points': 'sum'
    }).reset_index()

    early_rounds = draft_df[draft_df['round'] <= 3]  # First 3 rounds

    early_position_strategy = early_rounds.groupby(['team_name', 'year', 'position']).size().reset_index(name='early_picks')

    strategy_pivot = early_position_strategy.pivot_table(
        index=['team_name', 'year'],
        columns='position',
        values='early_picks',
        fill_value=0
    ).reset_index()

    strategy_performance = team_season_totals.merge(
        strategy_pivot,
        on=['team_name', 'year'],
        how='left'
    ).fillna(0)

    return strategy_performance


def analyze_draft_value_picks(draft_df, adp_df, selected_years):
    """
    Find the biggest steals and reaches compared to ADP
    """
    if draft_df.empty or adp_df.empty:
        return pd.DataFrame(), pd.DataFrame()

    draft_df_filtered = draft_df[draft_df['year'].isin(selected_years)]
    adp_df_filtered = adp_df[adp_df['year'].isin(selected_years)]

    draft_with_adp = draft_df_filtered.merge(
        adp_df_filtered[['Player', 'AVG Draft Position', 'year']],
        left_on=['player_name', 'year'],
        right_on=['Player', 'year'],
        how='inner'
    )

    if draft_with_adp.empty:
        return pd.DataFrame(), pd.DataFrame()

    draft_with_adp['adp_diff'] = draft_with_adp['pick'] - draft_with_adp['AVG Draft Position']

    draft_with_adp['value_score'] = draft_with_adp['season_points'] / draft_with_adp['pick']

    steals = draft_with_adp[
        (draft_with_adp['adp_diff'] > 12) &  # Drafted 12+ picks later than ADP
        (draft_with_adp['season_points'] > draft_with_adp['season_points'].quantile(0.6))
    ].nlargest(100, 'value_score')

    reaches = draft_with_adp[
        (draft_with_adp['adp_diff'] < -12) &  # Drafted 12+ picks earlier than ADP
        (draft_with_adp['season_points'] < draft_with_adp['season_points'].quantile(0.4))
    ].nsmallest(100, 'value_score')

    return steals, reaches


def create_draft_scatterplot_with_dynamic_trendline(draft_df, selected_positions, selected_years):
    """
    Create draft scatterplot with trend line that updates based on selected positions
    """
    filtered_draft_df = draft_df[
        draft_df['position'].isin(selected_positions) &
        draft_df['year'].isin(selected_years)
    ]

    if filtered_draft_df.empty:
        return go.Figure().add_annotation(
            text="No data available for selected positions",
            xref="paper", yref="paper", x=0.5, y=0.5, showarrow=False
        )

    fig = px.scatter(
        filtered_draft_df,
        x='pick',
        y='season_points',
        color='position',
        color_discrete_map=POSITION_COLORS,
        hover_data=['player_name', 'year', 'team_name', 'round'],
        title='Draft Position vs Season Points in Your League',
        labels={
            'pick': 'Draft Position in Your League',
            'season_points': 'Total Fantasy Points for Season',
            'position': 'Position'
        },
        height=500
    )

    try:
        x = filtered_draft_df['pick'].values
        y = filtered_draft_df['season_points'].values

        mask = ~(np.isnan(x) | np.isnan(y))
        x_clean = x[mask]
        y_clean = y[mask]

        if len(x_clean) > 1:
            z = np.polyfit(x_clean, y_clean, 1)
            p = np.poly1d(z)

            x_trend = np.linspace(x_clean.min(), x_clean.max(), 100)
            y_trend = p(x_trend)

            fig.add_scatter(
                x=x_trend,
                y=y_trend,
                mode='lines',
                name=f'Trend ({len(selected_positions)} positions)',
                line=dict(color='red', dash='dash', width=2),
                showlegend=True
            )

            correlation_matrix = np.corrcoef(x_clean, y_clean)
            correlation = correlation_matrix[0, 1]
            r_squared = correlation**2

            fig.add_annotation(
                x=0.02,
                y=0.98,
                xref="paper",
                yref="paper",
                text=f"R² = {r_squared:.3f}",
                showarrow=False,
                font=dict(size=12, color="red"),
                bgcolor="white",
                bordercolor="red",
                borderwidth=1
            )

    except Exception:
        pass

    fig.update_layout(
        xaxis_title="Draft Position (1 = First Pick)",
        yaxis_title="Total Fantasy Points for Season"
    )

    return fig


def _readable_text_color(hex_color):
    """Pick black or white text for readable contrast against hex_color."""
    hex_color = hex_color.lstrip('#')
    r, g, b = (int(hex_color[i:i + 2], 16) for i in (0, 2, 4))
    luminance = (0.299 * r + 0.587 * g + 0.114 * b) / 255
    return '#000000' if luminance > 0.6 else '#FFFFFF'


def create_draft_position_grid_html(draft_df, selected_positions):
    """
    Build a round x draft-slot grid (as an HTML table) showing which
    position was picked at each slot across all years, and how many
    fantasy points that player scored that season. Each cell holds one
    row per year in draft_df, stacked top to bottom in ascending year
    order, colored by position with the season point total as its
    label; a row is left blank when its position isn't in
    selected_positions. Unlike the scatterplot, this intentionally
    ignores the year sidebar filter - the whole point is comparing the
    same slot across every year that has data.
    """
    if draft_df.empty:
        return "<p>No draft data available.</p>"

    df = draft_df.copy()
    teams_per_year = df.groupby('year')['team_name'].nunique().to_dict()
    df['n_slots'] = df['year'].map(teams_per_year)
    df['pick_in_round'] = ((df['pick'] - 1) % df['n_slots']) + 1

    # Rank/average within each (position, year) across every drafted
    # player at that spot that year - independent of selected_positions,
    # so the ⭐/💩 benchmark doesn't shift as positions are toggled.
    df['pos_year_rank'] = df.groupby(['position', 'year'])['season_points'].rank(
        method='min', ascending=False
    )
    df['pos_year_avg'] = df.groupby(['position', 'year'])['season_points'].transform('mean')

    years = sorted(df['year'].unique())
    rounds = sorted(df['round'].unique())
    n_slots = int(df['n_slots'].max())
    slots = list(range(1, n_slots + 1))

    lookup = df.set_index(['year', 'round', 'pick_in_round'])[
        ['position', 'player_name', 'team_name', 'season_points', 'pos_year_rank', 'pos_year_avg']
    ].to_dict('index')

    parts = ['''
    <style>
    .draft-grid-wrap { overflow-x: auto; overflow-y: visible; }
    .draft-grid { border-collapse: collapse; font-size: 12px; }
    .draft-grid th, .draft-grid td { border: 1px solid rgba(128,128,128,0.3); padding: 3px; text-align: center; vertical-align: top; }
    .draft-grid th { background: rgba(128,128,128,0.15); font-weight: 600; white-space: nowrap; }
    .draft-round-label { background: rgba(128,128,128,0.15); font-weight: 600; white-space: nowrap; }
    .draft-cell { display: flex; flex-direction: column; gap: 2px; }
    .draft-swatch-detail { position: relative; }
    .draft-swatch-detail > summary { min-width: 40px; padding: 1px 4px; border-radius: 3px; font-size: 10px; line-height: 15px; white-space: nowrap; cursor: pointer; list-style: none; }
    .draft-swatch-detail > summary::-webkit-details-marker { display: none; }
    .draft-swatch-detail > summary::marker { content: ''; }
    .draft-swatch-popup { position: absolute; top: 100%; left: 0; z-index: 50; background: rgba(20,20,20,0.97); color: #fff; border: 1px solid rgba(255,255,255,0.25); border-radius: 4px; padding: 6px 8px; font-size: 11px; line-height: 1.5; white-space: nowrap; box-shadow: 0 2px 10px rgba(0,0,0,0.5); margin-top: 2px; text-align: left; }
    .draft-swatch-empty { min-width: 40px; height: 17px; border-radius: 3px; border: 1px dashed rgba(128,128,128,0.25); }
    .draft-legend { display: flex; flex-wrap: wrap; gap: 12px; margin: 6px 0 12px 0; font-size: 12px; }
    .draft-legend-item { display: flex; align-items: center; gap: 4px; }
    </style>
    ''']

    parts.append('<div class="draft-legend">')
    parts.append(f'<div class="draft-legend-item"><strong>Years per cell (top→bottom):</strong> {" → ".join(str(y) for y in years)}</div>')
    parts.append('<div class="draft-legend-item">Number shown = total fantasy points that season</div>')
    parts.append('<div class="draft-legend-item">Tap (or hover) a swatch for player details</div>')
    parts.append('<div class="draft-legend-item">⭐ = top 5 at that position that year · 💩 = below that position\'s average that year</div>')
    parts.append('</div>')

    parts.append('<div class="draft-grid-wrap"><table class="draft-grid"><thead><tr><th>Round</th>')
    for s in slots:
        parts.append(f'<th>Pick {s}</th>')
    parts.append('</tr></thead><tbody>')

    for rnd in rounds:
        parts.append(f'<tr><td class="draft-round-label">R{rnd}</td>')
        for s in slots:
            parts.append('<td><div class="draft-cell">')
            for yr in years:
                entry = lookup.get((yr, rnd, s))
                if entry and entry['position'] in selected_positions:
                    color = POSITION_COLORS.get(entry['position'], '#999999')
                    text_color = _readable_text_color(color)
                    pts = entry['season_points']
                    pts_label = f"{pts:.0f}" if pd.notna(pts) else "–"

                    marker = ''
                    marker_note = ''
                    if pd.notna(pts) and pd.notna(entry['pos_year_rank']) and entry['pos_year_rank'] <= 5:
                        marker = ' ⭐'
                        marker_note = ' - top 5 at position that year'
                    elif pd.notna(pts) and pd.notna(entry['pos_year_avg']) and pts < entry['pos_year_avg']:
                        marker = ' 💩'
                        marker_note = ' - below position average that year'

                    player = html.escape(str(entry['player_name']))
                    team = html.escape(str(entry['team_name']))
                    pos = html.escape(str(entry['position']))
                    title = f"{yr} R{rnd} Pick {s}: {entry['player_name']} ({entry['position']}) - {entry['team_name']} - {pts_label} pts{marker_note}"
                    parts.append(
                        f'<details name="draft-popup" class="draft-swatch-detail">'
                        f'<summary style="background:{color};color:{text_color}" title="{html.escape(title)}">{html.escape(pts_label)}{marker}</summary>'
                        f'<div class="draft-swatch-popup">'
                        f'<strong>{player}</strong><br>{pos} · {team}<br>{yr} R{rnd} Pick {s}<br>{html.escape(pts_label)} pts{marker}{html.escape(marker_note)}'
                        f'</div>'
                        f'</details>'
                    )
                else:
                    parts.append('<div class="draft-swatch-empty"></div>')
            parts.append('</div></td>')
        parts.append('</tr>')

    parts.append('</tbody></table></div>')

    return ''.join(parts)


# ---------------------------------------------------------------------------
# 2026 draft planning
# ---------------------------------------------------------------------------

# How many suggestions to surface per round. Early picks are close to
# deterministic (one clear call); later picks are a lottery, so show
# more shots on goal.
SUGGESTIONS_PER_ROUND = {
    **{r: 1 for r in range(1, 4)},
    **{r: 2 for r in range(4, 8)},
    **{r: 3 for r in range(8, 17)},
}


def normalize_adp_position(pos):
    """
    ADP files carry positions like 'RB', but also 'K1'/'K9' (kicker with
    a rank suffix), 'DS'/'DST' (defense) and IDP codes. Reduce them to
    the same vocabulary the draft/stats files use.
    """
    if not isinstance(pos, str):
        return 'Unknown'
    p = pos.strip().upper()
    p = re.sub(r'\d+$', '', p)  # 'K1' -> 'K', 'WR12' -> 'WR'
    if p in ('DS', 'DST', 'D/ST', 'DEF'):
        return 'DEF'
    if p in ('PK', 'K'):
        return 'K'
    if p in ('QB', 'RB', 'WR', 'TE'):
        return p
    return 'Unknown'


@st.cache_data
def load_adp_for_year(year):
    """
    Load a single season's ADP file (e.g. data/ADP_2026.csv), normalized
    to columns: player_name, position, adp. Returns an empty frame when
    that year's file hasn't been added yet.
    """
    path = Path(f"ff-dash/data/ADP_{year}.csv")
    if not path.exists():
        return pd.DataFrame(columns=['player_name', 'position', 'adp'])

    raw = pd.read_csv(path)

    name_col = next((c for c in ['Player', 'player_name', 'Name'] if c in raw.columns), None)
    pos_col = next((c for c in ['Pos', 'position', 'Position'] if c in raw.columns), None)
    adp_col = next(
        (c for c in ['AVG Draft Position', 'adp', 'ADP', 'AVG'] if c in raw.columns), None
    )
    if not (name_col and pos_col and adp_col):
        return pd.DataFrame(columns=['player_name', 'position', 'adp'])

    out = raw[[name_col, pos_col, adp_col]].copy()
    out.columns = ['player_name', 'position', 'adp']
    out['position'] = out['position'].apply(normalize_adp_position)
    out['adp'] = pd.to_numeric(out['adp'], errors='coerce')
    out = out.dropna(subset=['adp', 'player_name'])

    return out.sort_values('adp').reset_index(drop=True)


def compute_snake_picks(slot, n_teams, n_rounds=16):
    """
    Overall pick numbers owned by `slot` in a snake draft. Odd rounds run
    1..n_teams, even rounds reverse, so slot 2 of 10 owns 2, 19, 22, 39...
    """
    picks = []
    for rnd in range(1, n_rounds + 1):
        if rnd % 2 == 1:
            overall = (rnd - 1) * n_teams + slot
        else:
            overall = (rnd - 1) * n_teams + (n_teams - slot + 1)
        picks.append({'round': rnd, 'overall': overall})
    return picks


def compute_slot_blueprint(draft_df, slot, n_teams, n_rounds=16, window=3):
    """
    For each pick the slot owns, rank positions by how well they've
    worked at that spot historically.

    Two ingredients per position, measured over every pick within
    +/-`window` overall picks across all years in draft_df:
      availability - how often that position was actually taken there
      hit rate     - how often the player taken beat that position's
                     average score for that season

    confidence = 0.45*availability + 0.55*hit, pulled toward 50% by
    n/(n+4) so a 3-pick sample can't masquerade as a certainty. It's a
    weighting heuristic for ranking options, not a calibrated
    probability.
    """
    if draft_df.empty:
        return []

    d = draft_df.copy()
    pos_year_avg = d.groupby(['position', 'year'])['season_points'].mean().rename('pos_year_avg')
    d = d.merge(pos_year_avg, on=['position', 'year'])
    d['beat_avg'] = d['season_points'] > d['pos_year_avg']

    blueprint = []
    for pick in compute_snake_picks(slot, n_teams, n_rounds):
        overall = pick['overall']
        near = d[(d['pick'] >= overall - window) & (d['pick'] <= overall + window)]
        total = len(near)

        options = []
        for pos, grp in near.groupby('position'):
            n = len(grp)
            if n < 3 or pos == 'Unknown':
                continue
            availability = n / total
            hit = grp['beat_avg'].mean()
            raw = 0.45 * availability + 0.55 * hit
            confidence = 0.5 + (raw - 0.5) * (n / (n + 4))
            options.append({
                'position': pos,
                'confidence': round(confidence * 100),
                'availability': round(availability * 100),
                'hit_rate': round(hit * 100),
                'sample': n,
                'avg_points': round(grp['season_points'].mean()),
            })

        options.sort(key=lambda o: -o['confidence'])
        blueprint.append({**pick, 'options': options})

    return blueprint


def build_2026_draft_plan(draft_df, adp_df, slot, n_teams, n_rounds=16):
    """
    Pair the historical blueprint with a current ADP board to name real
    players. Walks rounds in order, only ever suggesting players who
    could plausibly still be on the board at that pick (ADP not far
    ahead of it), and never suggests the same player twice.

    Without an ADP board this still returns the blueprint - the position
    calls and confidence come from the league's own history and don't
    depend on ADP.
    """
    blueprint = compute_slot_blueprint(draft_df, slot, n_teams, n_rounds)
    has_adp = adp_df is not None and not adp_df.empty

    board = adp_df.copy() if has_adp else None
    taken = set()

    for row in blueprint:
        overall = row['overall']
        n_want = SUGGESTIONS_PER_ROUND.get(row['round'], 2)
        row['targets'] = []

        if not has_adp:
            continue

        # A player whose ADP is well ahead of this pick is realistically
        # gone; allow a small cushion for players who slide.
        available = board[(board['adp'] >= overall - 8) & (~board['player_name'].isin(taken))]

        for option in row['options']:
            if len(row['targets']) >= n_want:
                break
            candidates = available[available['position'] == option['position']]
            if candidates.empty:
                continue
            pick_row = candidates.iloc[0]
            taken.add(pick_row['player_name'])
            available = available[available['player_name'] != pick_row['player_name']]
            row['targets'].append({
                'player_name': pick_row['player_name'],
                'position': option['position'],
                'adp': pick_row['adp'],
                'confidence': option['confidence'],
                'hit_rate': option['hit_rate'],
                'avg_points': option['avg_points'],
                'sample': option['sample'],
            })

        # If the top positions are picked clean, fall back to best
        # available overall so the round still returns something usable.
        while len(row['targets']) < n_want and not available.empty:
            pick_row = available.iloc[0]
            taken.add(pick_row['player_name'])
            available = available[available['player_name'] != pick_row['player_name']]
            match = next(
                (o for o in row['options'] if o['position'] == pick_row['position']), None
            )
            row['targets'].append({
                'player_name': pick_row['player_name'],
                'position': pick_row['position'],
                'adp': pick_row['adp'],
                'confidence': match['confidence'] if match else None,
                'hit_rate': match['hit_rate'] if match else None,
                'avg_points': match['avg_points'] if match else None,
                'sample': match['sample'] if match else None,
            })

    return blueprint


def render_draft_plan_html(plan, has_adp):
    """Render build_2026_draft_plan()'s output as a compact round-by-round board."""
    if not plan:
        return "<p>No draft history available to build a plan from.</p>"

    parts = ['''
    <style>
    .plan { display: flex; flex-direction: column; gap: 10px; }
    .plan-round { border: 1px solid rgba(128,128,128,0.3); border-radius: 8px; overflow: hidden; }
    .plan-head { display: flex; align-items: center; gap: 10px; flex-wrap: wrap;
                 padding: 8px 12px; background: rgba(128,128,128,0.12); }
    .plan-rd { font-weight: 700; font-size: 15px; }
    .plan-ov { font-size: 11px; opacity: .7; border: 1px solid rgba(128,128,128,0.4);
               border-radius: 3px; padding: 1px 5px; font-variant-numeric: tabular-nums; }
    .plan-conf { margin-left: auto; display: flex; align-items: center; gap: 6px; }
    .plan-conf-n { font-size: 12px; font-weight: 600; opacity: .85; font-variant-numeric: tabular-nums; }
    .plan-bar { width: 52px; height: 5px; border-radius: 3px; background: rgba(128,128,128,0.3); overflow: hidden; }
    .plan-fill { height: 100%; background: #636EFA; border-radius: 3px; }
    .plan-why { padding: 7px 12px; font-size: 12.5px; opacity: .8;
                border-bottom: 1px solid rgba(128,128,128,0.25); }
    .plan-target { display: grid; grid-template-columns: 42px 1fr auto; gap: 10px;
                   align-items: center; padding: 8px 12px;
                   border-bottom: 1px solid rgba(128,128,128,0.18); }
    .plan-target:last-child { border-bottom: none; }
    .plan-pos { font-size: 11px; font-weight: 700; text-align: center; padding: 2px 0;
                border-radius: 3px; color: #fff; }
    .plan-name { font-weight: 600; font-size: 14px; }
    .plan-sub { display: block; font-weight: 400; font-size: 11px; opacity: .65; margin-top: 1px; }
    .plan-adp { font-size: 11.5px; opacity: .7; text-align: right;
                font-variant-numeric: tabular-nums; white-space: nowrap; }
    .plan-delta { display: block; font-size: 10.5px; margin-top: 1px; font-weight: 600; }
    .plan-delta.reach { color: #E8833A; }
    .plan-delta.value { color: #00A578; }
    .plan-delta.ontime { opacity: .55; font-weight: 400; }
    .plan-empty { padding: 10px 12px; font-size: 12.5px; opacity: .7; font-style: italic; }
    </style>
    <div class="plan">
    ''']

    for row in plan:
        top = row['options'][0] if row['options'] else None
        conf = top['confidence'] if top else 0
        parts.append('<div class="plan-round">')
        parts.append(
            f'<div class="plan-head"><span class="plan-rd">Round {row["round"]}</span>'
            f'<span class="plan-ov">pick {row["overall"]} overall</span>'
            f'<span class="plan-conf"><span class="plan-conf-n">{conf}%</span>'
            f'<span class="plan-bar"><span class="plan-fill" style="width:{conf}%"></span></span>'
            f'</span></div>'
        )

        if top:
            parts.append(
                f'<div class="plan-why">Historically at this pick: <b>{html.escape(top["position"])}</b> '
                f'taken {top["availability"]}% of the time, beating its position average '
                f'{top["hit_rate"]}% of the time for {top["avg_points"]} pts (n={top["sample"]}).</div>'
            )

        if row['targets']:
            for t in row['targets']:
                color = POSITION_COLORS.get(t['position'], '#999999')
                text_color = _readable_text_color(color)
                sub = (
                    f'{t["hit_rate"]}% hit rate here across {t["sample"]} picks'
                    if t['hit_rate'] is not None else 'best available on the board'
                )
                # ADP relative to the pick you actually own: a player whose
                # ADP sits well after your pick is one you'd be reaching for
                # (you can likely wait a round); one whose ADP is ahead of it
                # is falling to you.
                delta = t['adp'] - row['overall']
                if delta >= 10:
                    d_cls, d_txt = 'reach', f'reach {delta:.0f}'
                elif delta <= -5:
                    d_cls, d_txt = 'value', f'value {abs(delta):.0f}'
                else:
                    d_cls, d_txt = 'ontime', 'on time'
                parts.append(
                    f'<div class="plan-target">'
                    f'<span class="plan-pos" style="background:{color};color:{text_color}">'
                    f'{html.escape(t["position"])}</span>'
                    f'<span class="plan-name">{html.escape(str(t["player_name"]))}'
                    f'<span class="plan-sub">{html.escape(sub)}</span></span>'
                    f'<span class="plan-adp">ADP {t["adp"]:.1f}'
                    f'<span class="plan-delta {d_cls}">{d_txt}</span></span>'
                    f'</div>'
                )
        elif not has_adp:
            alts = ", ".join(
                f'{o["position"]} {o["confidence"]}%' for o in row['options'][:3]
            )
            parts.append(
                f'<div class="plan-empty">Position call ready — add ADP to name players. '
                f'Ranked here: {html.escape(alts)}</div>'
            )
        else:
            parts.append('<div class="plan-empty">No players left on the ADP board for this pick.</div>')

        parts.append('</div>')

    parts.append('</div>')
    return ''.join(parts)
